# Generated by Django 4.1.3 on 2025-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solucao', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=600)),
                ('nome_orientador', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('imagem_capa', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
