# Generated by Django 4.1.3 on 2025-04-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0002_solucao_delete_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solucao',
            name='imagem_capa',
        ),
    ]
